# Generated by Django 4.2.30 on 2026-08-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationlog",
            name="changes_made",
            field=models.JSONField(default=list),
        ),
    ]
